yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        verbose_name='Автор',
        related_name='posts')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст текст комментария'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:50]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='following'
    )

    class Meta:
        unique_together = ['user', 'author']

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Изображение',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )
        labels = {
            'text': 'Комментарий',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.shortcuts import render, get_object_or_404, redirect
from .utils import paginator_posts
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


@cache_page(20)
def index(request):
    posts = Post.objects.all()
    context = {
        'page_obj': paginator_posts(request, posts),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group,
        'page_obj': paginator_posts(request, posts),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'author': author,
        'page_obj': paginator_posts(request, posts),
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.select_related('author').all()
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=True)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id, author=request.user)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user
    )
    context = {'page_obj': paginator_posts(request, post_list)}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user, author__username=username).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{% if is_edit %}Редактировать пост {% else %}Новый пост{% endif %}{% endblock %}
{% load user_filters %}
{% block content %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  <title>Редактировать пост</title>
                {% else %}       
                  Добавить запись
                {% endif %}             
              </div>
              <div class="card-body">
                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                    {{ error|escape }}
                    </div>
                {% endfor %}
                {% endif %}
                {% if is_edit %}
                <form method="post" action="{% url 'posts:post_edit' post_id=post.pk %}" enctype="multipart/form-data">
                {% else %}
                <form method="post" action="{% url 'posts:post_create'%}" enctype="multipart/form-data">
                {% endif %}
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  {% csrf_token %}    
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">{{ form.text.label }}<span class="required text-danger" >*</span></label>
                      {{ form.text }}
                    <span class="helptext text-muted">{{ form.text.help_text }}</span>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">{{ form.group.label }}</label>
                      {{ form.group }}
                    <span class="helptext text-muted">{{ form.group.help_text }}</span>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">{{ form.image.label }}</label>
                      {{ form.image }}
                    <span class="helptext text-muted">{{ form.image.help_text }}</span>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% cache 20 sidebar %}
{% block title %}Ваши подписки{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
    <h1>Ваши подписки</h1>
  {% for post in page_obj %}
  <article>
    <ul>
        <dl class="row">
        {% if post.group %}
          <dt class="col-sm-3">Группа:</dt>
          <dd class="col-sm-9">{{ post.group.title }}</dd>
        {% endif %}
          <dt class="col-sm-3">Автор:</dt>
          <dd class="col-sm-9">{{ post.author.get_full_name }}</dd>
          <dt class="col-sm-3">Дата публикации:</dt>
          <dd class="col-sm-9">{{ post.pub_date|date:"d E Y" }}</dd>
          <dt class="col-sm-3">Пост:</dt>
          <dd class="col-sm-9" style="color: #4682B4">{{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
               <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          </dd>
        </dl>
    </ul>
    {% if post.group %}
      <button type="submit" class="btn btn-outline-primary">
        <a href="{% url 'posts:group_list' post.group.slug %}" style="text-decoration:none">
          Записи группы
        </a>
      </button>
      <button type="submit" style="text-decoration:none" class="btn btn-outline-primary" >
        <a href="{% url 'posts:profile' post.author.username %}" style="text-decoration:none">
                Все посты пользователя
        </a>
      </button>
    {% else %}
      <button type="submit" style="text-decoration:none" class="btn btn-outline-primary" >
        <a href="{% url 'posts:profile' post.author.username %}" style="text-decoration:none">
                Все посты пользователя
        </a>
      </button>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  </article>
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}
{% endcache %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
        <h1>{% block header %}{{ group.title }}{% endblock %}</h1>
        <p>{{ group.description }}</p>
      <article>
        {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}}
        {% include 'includes/paginator.html' %}
      </article>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% cache 20 sidebar %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
    <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
  <article>
    <ul>
        <dl class="row">
        {% if post.group %}
          <dt class="col-sm-3">Группа:</dt>
          <dd class="col-sm-9">{{ post.group.title }}</dd>
        {% endif %}
          <dt class="col-sm-3">Автор:</dt>
          <dd class="col-sm-9">{{ post.author.get_full_name }}</dd>
          <dt class="col-sm-3">Дата публикации:</dt>
          <dd class="col-sm-9">{{ post.pub_date|date:"d E Y" }}</dd>
          <dt class="col-sm-3">Пост:</dt>
          <dd class="col-sm-9" style="color: #4682B4">{{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
               <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          </dd>
        </dl>
    </ul>
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
    {% if post.group %}
      <button type="submit" class="btn btn-outline-primary">
        <a href="{% url 'posts:group_list' post.group.slug %}" style="text-decoration:none">
          Записи группы
        </a>
      </button>
      <button type="submit" style="text-decoration:none" class="btn btn-outline-primary" >
        <a href="{% url 'posts:profile' post.author.username %}" style="text-decoration:none">
                Все посты пользователя
        </a>
      </button>
    {% else %}
      <button type="submit" style="text-decoration:none" class="btn btn-outline-primary" >
        <a href="{% url 'posts:profile' post.author.username %}" style="text-decoration:none">
                Все посты пользователя
        </a>
      </button>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  </article>
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}
{% endcache %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block content %}
    <title>Пост {{ post|truncatechars:30 }}</title>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
              {% if post.group %}
              <li class="list-group-item">
                Группа: {{post.group.title}}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{post.author.username}}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{post.author.posts.count}}</span>
            </li>
            <li class="list-group-item">
              <button type="submit" class="btn btn-outline-primary">
                <a href="{% url 'posts:profile' post.author.username %}" style="text-decoration:none">
                Все посты пользователя
                </a>
              </button>
            </li>
        </ul>
      </aside>
        <article class="col-12 col-md-9">
           {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
               <img class="card-img my-2" src="{{ im.url }}">
           {% endthumbnail %}
           <p>
               {{ post.text|linebreaksbr }}
           </p>
           <button type="submit" class="btn btn-outline-primary">
               <a href="{% url 'posts:post_edit' post_id=post.pk %}" style="text-decoration:none">
                 Редактировать
               </a>
           </button>
        </article>
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
<div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
  {% endif %}
</div>
<article>
{% for post in page_obj %}
  <ul>
        <dl class="row">
        {% if post.group %}
          <dt class="col-sm-3">Группа:</dt>
          <dd class="col-sm-9">{{ post.group.title }}</dd>
        {% endif %}
          <dt class="col-sm-3">Автор:</dt>
          <dd class="col-sm-9">{{ post.author.get_full_name }}</dd>
          <dt class="col-sm-3">Дата публикации:</dt>
          <dd class="col-sm-9">{{ post.pub_date|date:"d E Y" }}</dd>
          <dt class="col-sm-3">Пост:</dt>
          <dd class="col-sm-9" style="color: #4682B4">{{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
               <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          </dd>
        </dl>
    </ul>
    <button type="submit" style="text-decoration:none" class="btn btn-outline-primary" >
      <a href='{% url 'posts:post_detail' post.pk %}' style="text-decoration:none">
          Подробнее ..
      </a>
    </button>
</article>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
    {% include 'includes/paginator.html' %}
{% endblock %}